network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
    eth1:
      dhcp4: false
      addresses:
      - 1.2.3.4/24
      routes:
      - to: 10.0.0.0/8
        via: 1.2.3.1
