#! /usr/bin/bash
clear
echo
echo "********************************* description ********************************************************"
echo "*                                                                                                    *"
echo "*                                                                                                    *"
echo "*                  Retirementhome of the Rocket Trutles, Hamburg 2024                                *"
echo "*                                                                                                    *"
echo "*                                                                                                    *"
echo "*    Der Plan fuer das Wochenende....und die Woche zum Testen...                                     *"
echo "*    .B IP            09.11.2024     ok                                                              *"
echo "*    .C BGP (RR)      09.11.2024                                                                     *"
echo "*    .D BGP eBGP      09.11.2024                                                                     *"
echo "*    .E MC                                                                                           *"
echo "*    .F VxLAN         09.11.2024                                                                     *"
echo "*    .G EVPN L2       10.11.2024                                                                     *"
echo "*                                                                                                    *"
echo "************************************* end ************************************************************"
echo
echo 
PS3='Please enter your choice: '
options=("IP Setup" "iBGP" "eBGP" "VxLAN" "EVPN L2" "Cleanup" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "IP Setup")
            echo "Adressen werden gesetzt"
            sudo ansible-playbook -i /home/cumulus/HH/inventory/files/hosts /home/cumulus/HH/.B/main.yaml
            break
            ;;
        "iBGP")
            echo "iBGP"
            sudo ansible-playbook -i /home/cumulus/HH/inventory/files/hosts /home/cumulus/HH/.C/main.yaml
            break
            ;;
        "eBGP")
            echo "eBGP"
            sudo ansible-playbook -i /home/cumulus/HH/inventory/files/hosts /home/cumulus/HH/.D/main.yaml
            break
            ;;
        "VxLAN")
            echo "Statischer Tunnel"
            sudo ansible-playbook -i /home/cumulus/HH/inventory/files/hosts /home/cumulus/HH/.F/main.yaml
            break
            ;;
        "EVPN L2")
            echo "EVPN L2"
            sudo ansible-playbook -i /home/cumulus/HH/inventory/files/hosts /home/cumulus/HH/.G/main.yaml
            break
            ;;
        "Cleanup")
            echo "cleaning up the environment"
            sudo ansible-playbook -i /home/cumulus/HH/inventory/files/hosts /home/cumulus/HH/.cleanup/main.yaml
            break
            ;;
         "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
