#! /usr/bin/bash
clear
echo
echo "********************************* description ********************************************************"
echo "*                                                                                                    *"
echo "*                                                                                                    *"
echo "*                  Retirementhome of the Rocket Trutles, Hamburg 2024                                *"
echo "*                                                                                                    *"
echo "*                                                                                                    *"
echo "*    Der Plan fuer das Wochenende....                                                                *"
echo "*    .B IP            09.11.2024                                                                     *"
echo "*    .C BGP RR        09.11.2024                                                                     *"
echo "*    .D BGP eBGP                                                                                     *"
echo "*    .E MC                                                                                           *"
echo "*    .F VxLAN                                                                                        *"
echo "*    .G EVPN L2                                                                                      *"
echo "*    .H EVPN L3                                                                                      *"
echo "*                                                                                                    *"
echo "************************************* end ************************************************************"
echo
echo 
PS3='Please enter your choice: '
options=("IP Setup" "iBGP" "Cleanup" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "IP Setup")
            echo "Adressen werden gesetzt"
            sudo ansible-playbook -i /home/cumulus/HH/inventory/files/hosts /home/cumulus/HH/.B/main.yaml
            break
            ;;
        "iBGP")
            echo "iBGP"
            sudo ansible-playbook -i /home/cumulus/HH/inventory/files/hosts /home/cumulus/HH/.C/main.yaml
            break
            ;;
        "Cleanup")
            echo "cleaning up the environment"
            sudo ansible-playbook -i /home/cumulus/HH/inventory/files/hosts /home/cumulus/HH/.cleanup/main.yaml
            break
            ;;
         "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
