#! /usr/bin/bash

# ALQ, 汉堡 二零二四 年

CUMULUS_HOME="/home/cumulus"

sudo ansible-playbook /home/ubuntu/HH/.main.yaml

echo "User ueberpruefen"
echo "Directory ueberpruefen"

sudo -i -u cumulus bash << EOF
  cd "$CUMULUS_HOME"
  echo "DIR :$PWD"
  if [ ! -d "$CUMULUS_HOME/HH" ]; then
    git clone https://github.com/laquiante/HH
    echo "git clone done"
  fi
  if [ -d "$CUMULUS_HOME/HH" ]; then
    cd $CUMULUS_HOME/HH
    sudo chmod 744 $CUMULUS_HOME/HH/start.sh
    export PATH="$CUMULUS_HOME/HH/:$PATH" 
    echo "calling /home/cumulus/HH/start.sh"
    sudo bash "$CUMULUS_HOME/HH/start.sh"
  fi

EOF
#clear
exit 0 
