#! /usr/bin/bash
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Wittduen 2025

#clear
echo "Netplan"
sudo ansible-playbook -i /home/cumulus/HL/inventory/files/hosts /home/cumulus/HL/.netplan/hosts.yaml
echo "start script: running additional configuration items" 
if [ -f /home/cumulus/HL/.additional.conf ]; then
        . /home/cumulus/HL/.additional.conf
fi
echo "Fertig"
exit 0
